apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello10
spec:
  selector:
    matchLabels:
      app: hello10
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: hello10
    spec:
      containers:
      - name: hello10
        image: hashicorp/http-echo
        args: ["-text=Hello world (1)"]
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello10
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5678
  selector:
    app: hello10

