apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello1
spec:
  selector:
    matchLabels:
      app: hello1
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: hashicorp/http-echo
        args: ["-text=Hello world (10)"]
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello1
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  selector:
    app: hello10
