apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello2
spec:
  selector:
    matchLabels:
      app: hello2
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - name: hello2
        image: hashicorp/http-echo
        args: ["-text=Hello world (2)"]
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: hello2
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
    nodePort: 3036
  selector:
    app: hello2
