apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: not-k8s-extra
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: not-k8s-extra
  minReplicas: 5
  maxReplicas: 10